### ISSUE TITLE
cant import cannyEdgeDetector from 'canny-edge-detector'

### ISSUE THREAD

**Issue by umeshravuru** [image-js/canny-edge-detector#3]
When i run the basic example you provided in the readMe, i am getting this error

`(function (exports, require, module, __filename, __dirname) { import cannyEdgeDetector from 'canny-edge-detector';`

https://ibb.co/ihAg48

**Comment by stropitek** [comment]
Hello

I've updated the README example to use commonJS instead of ES modules. It should work out of the box with nodejs.
